dvision:
  field_model:
    field_length:           900
    field_width:            600
    goal_depth:             60
    goal_width:             260
    goal_height:            180
    goal_area_length:       100
    goal_area_width:        500
    penalty_mark_distance:  210
    center_circle_diameter: 150
    border_strip_width:     70
    ball_diameter:          15

  monitor:
    use_cv_show:            true
    transmit_raw_img:       false
    update_gui_img:         true
    update_canny_img:       false
    update_field_binary:    false
    update_goal_binary:     false
    update_line_binary:     false
    update_obstacle_binary: false
